name: Deploy with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Ansible
      working-directory: ./deploy
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        sudo pip install ansible
        ansible-galaxy collection install community.docker
        sudo echo -e "[server]\n${{secrets.SERVER_IP}}" > inventory.ini

    - name: Run Ansible Playbook
      working-directory: ./deploy
      run: ansible-playbook -vvv playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
