name: Deploy Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.docker

      - name: Make Inventory
        working-directory: ./deploy
        run: |
          echo "[server]" > ./inventory.ini
          echo "${{secrets.SERVER_IP}}" >> ./inventory.ini
        env:
          SERVER_IP: ${{secrets.SERVER_IP}}

      - name: Setup SSH Key
        working-directory: ./deploy
        run: echo '${{secrets.SSH_PRIVATE_KEY}}' > ./ssh-key
  
      - name: Set Permissions for SSH Key
        working-directory: ./deploy
        run: chmod 600 ./ssh-key

      - name: Run Ansible Playbook
        working-directory: ./deploy
        run: ansible-playbook --private-key=ssh-key playbook.yml
