name: Deploy Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH 
        shell: bash
        run: |
         eval `ssh-agent -s`
         mkdir -p /home/runner/.ssh/
         touch /home/runner/.ssh/id_rsa
         echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
         chmod 700 /home/runner/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.docker

      - name: Make Inventory
        working-directory: ./deploy
        shell: bash
        run: |
          touch ./inventory.ini
          echo -e "[server]\n${{secrets.SERVER_IP}}" > ./inventory.ini
          cat inventory.ini

      - name: Run Ansible Playbook
        working-directory: ./deploy
        shell: bash
        run: ansible-playbook -vvv --private-key /home/runner/.ssh/id_rsa playbook.yml
