name: Deploy with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./deploy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible
        # sudo pip install ansible

    - name: Install Ansible Collections
      run: ansible-galaxy collection install community.docker  

    - name: Create Inventory;
      run: sudo echo -e "[server]\n${{secrets.SERVER_IP}}" > inventory.ini

    - name: Run Ansible Playbook
      run: ansible-playbook playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
